src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_crea;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_modif;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="Id", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\OneToMany(targetEntity=TagArticle::class, mappedBy="id_article", orphanRemoval=true)
     */
    private $tagArticles;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="id_article", orphanRemoval=true)
     */
    private $commentaires;

    public function __construct()
    {
        $this->tagArticles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCrea(): ?\DateTimeInterface
    {
        return $this->date_crea;
    }

    public function setDateCrea(\DateTimeInterface $date_crea): self
    {
        $this->date_crea = $date_crea;

        return $this;
    }

    public function getDateModif(): ?\DateTimeInterface
    {
        return $this->date_modif;
    }

    public function setDateModif(\DateTimeInterface $date_modif): self
    {
        $this->date_modif = $date_modif;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    /**
     * @return Collection|TagArticle[]
     */
    public function getTagArticles(): Collection
    {
        return $this->tagArticles;
    }

    public function addTagArticle(TagArticle $tagArticle): self
    {
        if (!$this->tagArticles->contains($tagArticle)) {
            $this->tagArticles[] = $tagArticle;
            $tagArticle->setIdArticle($this);
        }

        return $this;
    }

    public function removeTagArticle(TagArticle $tagArticle): self
    {
        if ($this->tagArticles->contains($tagArticle)) {
            $this->tagArticles->removeElement($tagArticle);
            // set the owning side to null (unless already changed)
            if ($tagArticle->getIdArticle() === $this) {
                $tagArticle->setIdArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setIdArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdArticle() === $this) {
                $commentaire->setIdArticle(null);
            }
        }

        return $this;
    }
}

templates/pages/pageAccueil.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<!-- TODO MediaQueries a faire  -->
	<div class="container">
		{% if article==[] %}
			Aucun résultat (╯°□°）╯︵ ┻━┻
		{% else %}
			<div class="container-flex">

				{%for art in article %}
					<div class="card" style="width: 30%; margin-bottom: 2%;">
						<div class="card-header">
							<h5>
								<strong>{{ art.getTitre() }}</strong>
							</h5>
						</div>
						<div class="card-body" style="padding-top: 3px">
							<small>{{ art.getDateCrea() |date('Y-m-d H:i:s')}}</small>
							<p class="card-text">{{ art.getContenu() }}</p>
							<a href="pageDetail/?id={{ art.getId }}" class="btn btn-outline-primary">Voir plus</a>
						</div>
					</div>
				{% endfor %}

			</div>
		{% endif %}
	</div>
</div>{% endblock %}

templates/pages/pageDetail.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{article[0].titre}}
{% endblock %}
{% block body %}
	<div class="container">
		<div class="jumbotron mt-5">
			<div class="col-sm-8 mx-auto">
				<h1 class="text-center">{{ article[0].titre }}</h1>
			</div>
			<br>
			<small>{{ article[0].dateModif |date('Y-m-d H:i:s') }}</small>
			<div style="text-align: center;">
				<p>{{ article[0].contenu }}</p>
			</div>
			<small>{{ article[0].getIdUser().nom }}
				{{ article[0].getIdUser().prenom }}</small>

		</div>
	</div>
{% endblock %}